import type { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Terms of Service • Recipe Collector",
  description: "Terms of service and culinary guidelines for Recipe Collector.",
};

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-[#faf8f5] dark:bg-[#12100e] text-stone-900 dark:text-stone-100 px-4 py-12 sm:px-6 lg:px-8 transition-colors duration-300">
      <div className="mx-auto max-w-4xl space-y-8">
        
        {/* HEADER */}
        <header className="space-y-3 border-b border-stone-200 dark:border-white/10 pb-8">
          <div className="inline-flex items-center gap-2 rounded-full border border-amber-500/20 bg-amber-500/10 px-3.5 py-1 text-xs font-bold text-amber-700 dark:text-amber-400">
            Legal &amp; Compliance
          </div>
          <h1 className="text-3xl sm:text-4xl font-extrabold tracking-tight text-stone-950 dark:text-white">
            Terms of Service
          </h1>
          <p className="text-xs sm:text-sm font-medium text-stone-500 dark:text-stone-400">
            Last updated: September 13, 2026
          </p>
        </header>

        {/* CONTENT BENTO SECTIONS */}
        <div className="space-y-6 text-sm sm:text-base leading-relaxed text-stone-700 dark:text-stone-300">
          
          <section className="rounded-3xl border border-stone-200/90 bg-white dark:border-white/10 dark:bg-[#181411] p-6 sm:p-8 space-y-3 shadow-xs">
            <h2 className="text-lg sm:text-xl font-bold text-stone-900 dark:text-white">
              1. Acceptance of Terms
            </h2>
            <p>
              By accessing or using Recipe Collector (the &quot;Service&quot;), you agree to be bound by these Terms of Service. If you do not agree to these terms, please do not use our services.
            </p>
          </section>

          <section className="rounded-3xl border border-stone-200/90 bg-white dark:border-white/10 dark:bg-[#181411] p-6 sm:p-8 space-y-3 shadow-xs">
            <h2 className="text-lg sm:text-xl font-bold text-stone-900 dark:text-white">
              2. Culinary &amp; Nutritional Disclaimer
            </h2>
            <p className="bg-amber-500/5 dark:bg-amber-500/10 border border-amber-500/20 rounded-2xl p-4 text-xs sm:text-sm text-stone-800 dark:text-stone-200">
              <strong>Important Notice:</strong> All nutritional facts, calorie counts, ingredient measurements, and culinary tips provided on Recipe Collector are algorithmic approximations generated by computational heuristics and AI. They do not constitute medical, dietary, or allergen advice. Always exercise proper hygiene and verify ingredients against your dietary allergies.
            </p>
          </section>

          <section className="rounded-3xl border border-stone-200/90 bg-white dark:border-white/10 dark:bg-[#181411] p-6 sm:p-8 space-y-3 shadow-xs">
            <h2 className="text-lg sm:text-xl font-bold text-stone-900 dark:text-white">
              3. Community Standards &amp; Content Moderation
            </h2>
            <p>
              Recipe Collector is committed to a safe, welcoming, and inspiring community for home cooks and chefs alike. When publishing recipes, comments, or cook photos, you agree not to post:
            </p>
            <ul className="list-disc list-inside space-y-1.5 pl-2 text-xs sm:text-sm text-stone-600 dark:text-stone-400">
              <li>Inappropriate, offensive, or defamatory content.</li>
              <li>Spam, promotional links, or commercial solicitations.</li>
              <li>Content that infringes on third-party copyrights or trademarks.</li>
              <li>Misleading, hazardous, or non-food safe preparation techniques.</li>
            </ul>
            <p className="text-xs sm:text-sm pt-2">
              Our safety system allows users to flag objectionable content. Content receiving multiple reports will be quarantined for human administrative review. Administrators reserve the right to remove content or suspend accounts violating these standards.
            </p>
          </section>

          <section className="rounded-3xl border border-stone-200/90 bg-white dark:border-white/10 dark:bg-[#181411] p-6 sm:p-8 space-y-3 shadow-xs">
            <h2 className="text-lg sm:text-xl font-bold text-stone-900 dark:text-white">
              4. User Content &amp; Ownership
            </h2>
            <p>
              You retain all ownership rights to the recipes, photos, and journal entries you create on Recipe Collector. By marking a recipe as public, you grant Recipe Collector a worldwide, non-exclusive license to display and index that recipe within our Explore catalog.
            </p>
            <p className="text-xs sm:text-sm">
              You can switch any recipe back to private or delete it at any time.
            </p>
          </section>

          <section className="rounded-3xl border border-stone-200/90 bg-white dark:border-white/10 dark:bg-[#181411] p-6 sm:p-8 space-y-3 shadow-xs">
            <h2 className="text-lg sm:text-xl font-bold text-stone-900 dark:text-white">
              5. Account Termination &amp; Data Deletion
            </h2>
            <p>
              You may terminate your account at any time via Account Settings. Under GDPR regulations, requesting account deletion permanently purges your credentials, recipes, photos, and preferences from our active databases.
            </p>
          </section>

          <section className="rounded-3xl border border-stone-200/90 bg-white dark:border-white/10 dark:bg-[#181411] p-6 sm:p-8 space-y-3 shadow-xs">
            <h2 className="text-lg sm:text-xl font-bold text-stone-900 dark:text-white">
              6. Contact Us
            </h2>
            <p>
              If you have any questions about these Terms of Service, please reach out to us at{" "}
              <span className="font-semibold text-amber-600 dark:text-amber-400">legal@recipecollector.app</span>.
            </p>
          </section>

        </div>

        {/* FOOTER NAVIGATION */}
        <div className="pt-4 flex items-center justify-between border-t border-stone-200 dark:border-white/10 text-xs font-semibold">
          <Link href="/" className="hover:text-amber-600 dark:hover:text-amber-400 transition">
            ← Back to Explore
          </Link>
          <Link href="/privacy" className="hover:text-amber-600 dark:hover:text-amber-400 transition">
            Privacy Policy →
          </Link>
        </div>

      </div>
    </div>
  );
}
